pub const BLOCKS_IN_CHUNK: usize = 16;

pub const BLOCKS_IN_SECTION_Y: usize = 16;
pub const SECTIONS_Y: usize = 16;
pub const BLOCKS_Y: usize = BLOCKS_IN_SECTION_Y * SECTIONS_Y; // 256

pub const BLOCKS_IN_CHUNK_2D: usize = BLOCKS_IN_CHUNK * BLOCKS_IN_CHUNK; // 256
pub const BLOCKS_IN_CHUNK_3D: usize = BLOCKS_IN_CHUNK_2D * BLOCKS_Y; // 65536

pub const BLOCKS_IN_SECTION_3D: usize = BLOCKS_IN_CHUNK_2D * BLOCKS_IN_SECTION_Y; // 4096
// pub const BLOCKS_IN_CHUNK_3D: usize = BLOCKS_IN_SECTION_3D * SECTIONS_Y; // 65536

pub const CHUNKS_IN_REGION: usize = 32;
pub const CHUNKS_IN_REGION_2D: usize = CHUNKS_IN_REGION * CHUNKS_IN_REGION; // 1024
// pub const BLOCKS_IN_REGION: usize = CHUNKS_IN_REGION * BLOCKS_IN_CHUNK; // 512

pub const SECTOR_SIZE: usize = 4096;
